## NumPy
尽管 Python 的列表本身已经非常强大，但 NumPy 具备许多关键特性，使其相比 Python 列表具有显著优势。下面是几个非常有说服力的特性：  

### 首先是速度。
当对大型数组执行操作时，NumPy 往往能够比 Python 列表快上几个数量级。这种速度优势来源于 NumPy 数组的 内存高效性，以及 NumPy 在执行算术运算、统计运算和线性代数运算时所使用的 高度优化的算法。

### 另一个重要特性是多维数组的数据结构。
NumPy 提供了能够表示 向量和矩阵 的多维数组。你将在本课程的线性代数部分学习到关于向量和矩阵的知识，并很快会看到，许多机器学习算法都依赖矩阵运算。例如，在训练神经网络时，通常需要执行大量的矩阵乘法。NumPy 针对矩阵运算做了优化，它让我们能够 高效、有效地进行线性代数运算，因此非常适合用于解决机器学习问题。

### NumPy 相较于 Python 列表的另一个巨大优势在于它提供了大量优化过的内置数学函数。
这些函数允许你非常快速地完成各种复杂的数学计算，并且只需极少的代码（避免使用复杂的循环），从而让你的程序更加 简洁、可读、易于理解。  

官方[NumPy使用手册](https://numpy.org/doc/stable/user/index.html)

In [3]:
import numpy as np

# 一维数组
a = np.array([1, 2, 3])
print(a)          # [1 2 3]
print(a.shape)    # (3,)

# 二维数组
b = np.array([[1, 2, 3], [4, 5, 6]])
print('b = ', b)
print('b has dimensions:', b.shape)
print('b is an object of type:', type(b))
print('The elements in b are of type:', b.dtype)

[1 2 3]
(3,)
b =  [[1 2 3]
 [4 5 6]]
b has dimensions: (2, 3)
b is an object of type: <class 'numpy.ndarray'>
The elements in b are of type: int64


In [4]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c[0,1])      # 2 (第一行第二列)
print(c[:,1])      # [2 5 8] (第二列)
print(c[0:2, :])   # 前两行

2
[2 5 8]
[[1 2 3]
 [4 5 6]]


np.zeros((2,3))       # 2x3 全零数组.  
np.ones((3,3))        # 3x3 全一数组.  
np.eye(3)             # 3x3 单位矩阵.  
np.arange(0,10,2)     # [0 2 4 6 8].  
np.linspace(0,1,5)    # 等间隔 [0.   0.25 0.5 0.75 1.]   
np.full((2,3), 5)     # 2x3 全5数组  
np.diag([10,20,30,50])#对角矩阵  
np.reshape(array, newshape, order='C')[source] # 改变数组形状 的方法，但不会改变数组的数据内容    
np.random.random(shape) # 生成[0,1)区间均匀分布的随机浮点数。  
np.random.randint(start, stop, size = shape) #生成指定范围内的随机整数。  
np.random.normal(mean, standard deviation, size=shape) #用来生成 服从正态分布 (高斯分布) 的随机数。  
np.delete(arr, obj, axis=None) #删除数组中的元素.  
np.append(array, values, axis=None) #向数组末尾追加值，返回新数组（不会在原数组上修改）。  
np.insert(ndarray, index, elements, axis) #在指定位置插入元素，支持 1D 和多维数组操作。多维数组先展平   
np.hstack(sequence_of_ndarray) #水平方向（列方向，axis=1）拼接数组.  
np.vstack(sequence_of_ndarray) #垂直方向（行方向，axis=0）拼接数组。 
np.copy() #创建一个 数组的副本（copy）。返回的新数组和原数组 数据相同，但内存地址不同。  
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None). #找出数组中的 唯一值（去重），并且可以选择返回：排序后的唯一值,唯一值对应的索引,唯一值的出现次数  
np.intersect1d(x,y) #x,y的交集  
np.setdiff1d(x,y) #x中有y中没有的元素  
np.union1d(x,y) #x，y的并集  
ndarray.sort(axis=-1, kind=None, order=None) #排序。


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]   (逐元素相加)
print(a - b)   # [-3 -3 -3] (逐元素相减)
print(a * b)   # [ 4 10 18] (逐元素相乘)
print(a / b)   # [0.25 0.4  0.5] (逐元素相除)
print(a ** 2)  # [1 4 9]   (平方)
print(np.sqrt(a)) # [1.         1.41421356 1.73205081] (平方根)
print(np.exp(a)) # [ 2.71828183  7.3890561  20.08553692] (指数)
print(np.power(a,2)) # [1 4 9] (幂)
print(np.dot(a, b)) # 32 (点积)
print(np.sum(a))    # 6 (求和)
print(np.mean(a))   # 2.0 (均值)
print(np.std(a))    # 0.816496580927726 (标准差)
print(np.max(a))    # 3 (最大值)
print(np.min(a))    # 1 (最小值)    
print(np.argmax(a)) # 2 (最大值索引)
print(np.argmin(a)) # 0 (最小值索引)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[1 4 9]
32
6
2.0
0.816496580927726
3
1
2
0


当两个数组形状 (shape) 不同时，NumPy 会尝试 自动扩展 较小的数组，使它们兼容后再运算。

广播规则.  
- 如果维度不同，自动在前面补 1。
- 如果某个维度大小不同，但其中一个是 1，则扩展为另一个的大小。
- 如果某个维度大小不同，且都不为 1，则报错。